/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import 'sst';
declare module 'sst' {
	export interface Resource {
		PreviewWeb: {
			type: 'sst.aws.Astro';
			url: string;
		};
	}
}
// cloudflare
import * as cloudflare from '@cloudflare/workers-types';
declare module 'sst' {
	export interface Resource {
		AgiSh: cloudflare.Service;
		OGCache: cloudflare.KVNamespace;
		PreviewApi: cloudflare.Service;
		PreviewDB: cloudflare.D1Database;
	}
}

import 'sst';
export {};
