/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import 'sst';
declare module 'sst' {
	export interface Resource {
		AnthropicApiKey: {
			type: 'sst.sst.Secret';
			value: string;
		};
		DatabaseUrl: {
			type: 'sst.sst.Secret';
			value: string;
		};
		GoogleAiApiKey: {
			type: 'sst.sst.Secret';
			value: string;
		};
		MoonshotAiApiKey: {
			type: 'sst.sst.Secret';
			value: string;
		};
		OpenAiApiKey: {
			type: 'sst.sst.Secret';
			value: string;
		};
		PlatformWallet: {
			type: 'sst.sst.Secret';
			value: string;
		};
		PreviewWeb: {
			type: 'sst.aws.Astro';
			url: string;
		};
	}
}
// cloudflare
import * as cloudflare from '@cloudflare/workers-types';
declare module 'sst' {
	export interface Resource {
		AgiSh: cloudflare.Service;
		OGCache: cloudflare.KVNamespace;
		PreviewApi: cloudflare.Service;
		PreviewDB: cloudflare.D1Database;
	}
}

import 'sst';
