/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AgiSh": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MoonshotAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OGCache": {
      "type": "sst.cloudflare.Kv"
    }
    "OGFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PlatformWallet": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PreviewApi": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "PreviewDB": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
    "PreviewWeb": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "Setu": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}