/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
type ImportMetaEnv = {};
interface ImportMeta {
	readonly env: ImportMetaEnv;
}
