import { SyntaxStyle, RGBA } from '@opentui/core';

export const colors = {
	bg: '#1a1b26',
	bgDark: '#16161e',
	bgHighlight: '#292e42',
	bgSubtle: '#1f2335',

	fg: '#c0caf5',
	fgBright: '#e6edf3',
	fgMuted: '#a9b1d6',
	fgDark: '#565f89',
	fgDimmed: '#3b4261',

	blue: '#7aa2f7',
	green: '#9ece6a',
	red: '#f7768e',
	yellow: '#e0af68',
	purple: '#bb9af7',
	cyan: '#7dcfff',
	orange: '#ff9e64',
	teal: '#73daca',
	magenta: '#c678dd',

	border: '#292e42',
	borderActive: '#7aa2f7',
	borderSubtle: '#1f2335',

	toolBg: '#1e2030',
	toolFg: '#3b4261',
	toolIcon: '#414868',
	toolName: '#565f89',
	toolArgs: '#3b4261',

	userBg: '#1a1b26',
	assistantBg: '#1e2030',

	userBadge: '#7aa2f7',
	assistantBadge: '#bb9af7',
	systemBadge: '#565f89',

	streamDot: '#9ece6a',
	errorBg: '#2d202a',
};

export const syntaxStyle = SyntaxStyle.fromStyles({
	keyword: { fg: RGBA.fromHex('#FF7B72'), bold: true },
	'keyword.import': { fg: RGBA.fromHex('#FF7B72'), bold: true },
	'keyword.operator': { fg: RGBA.fromHex('#FF7B72') },
	string: { fg: RGBA.fromHex('#A5D6FF') },
	comment: { fg: RGBA.fromHex('#8B949E'), italic: true },
	number: { fg: RGBA.fromHex('#79C0FF') },
	boolean: { fg: RGBA.fromHex('#79C0FF') },
	constant: { fg: RGBA.fromHex('#79C0FF') },
	function: { fg: RGBA.fromHex('#D2A8FF') },
	'function.call': { fg: RGBA.fromHex('#D2A8FF') },
	'function.method.call': { fg: RGBA.fromHex('#D2A8FF') },
	type: { fg: RGBA.fromHex('#FFA657') },
	constructor: { fg: RGBA.fromHex('#FFA657') },
	variable: { fg: RGBA.fromHex('#E6EDF3') },
	'variable.member': { fg: RGBA.fromHex('#79C0FF') },
	property: { fg: RGBA.fromHex('#79C0FF') },
	operator: { fg: RGBA.fromHex('#FF7B72') },
	punctuation: { fg: RGBA.fromHex('#F0F6FC') },
	'punctuation.bracket': { fg: RGBA.fromHex('#F0F6FC') },
	'punctuation.delimiter': { fg: RGBA.fromHex('#C9D1D9') },
	default: { fg: RGBA.fromHex('#E6EDF3') },
	'markup.heading': { fg: RGBA.fromHex('#58A6FF'), bold: true },
	'markup.heading.1': { fg: RGBA.fromHex('#00FF88'), bold: true, underline: true },
	'markup.heading.2': { fg: RGBA.fromHex('#00D7FF'), bold: true },
	'markup.bold': { fg: RGBA.fromHex('#F0F6FC'), bold: true },
	'markup.strong': { fg: RGBA.fromHex('#F0F6FC'), bold: true },
	'markup.italic': { fg: RGBA.fromHex('#F0F6FC'), italic: true },
	'markup.list': { fg: RGBA.fromHex('#FF7B72') },
	'markup.quote': { fg: RGBA.fromHex('#8B949E'), italic: true },
	'markup.raw': { fg: RGBA.fromHex('#A5D6FF') },
	'markup.raw.block': { fg: RGBA.fromHex('#A5D6FF') },
	'markup.link': { fg: RGBA.fromHex('#58A6FF'), underline: true },
	'markup.link.url': { fg: RGBA.fromHex('#58A6FF'), underline: true },
});
