name: Release (beta)

on:
  push:
    branches:
      - beta
  workflow_dispatch:
    inputs:
      bump:
        description: "Prerelease bump type"
        required: false
        default: prerelease
        type: choice
        options:
          - prerelease
      preid:
        description: "Prerelease identifier"
        required: false
        default: beta

jobs:
  release:
    if: ${{ github.event_name != 'push' || (github.event.head_commit != null && !startsWith(github.event.head_commit.message, 'chore(release-beta):')) }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      BUMP_TYPE: ${{ github.event_name == 'workflow_dispatch' && inputs.bump || 'prerelease' }}
      PREID: ${{ github.event_name == 'workflow_dispatch' && inputs.preid || 'beta' }}
      DIST_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.preid || 'beta' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Verify npm token
        if: ${{ secrets.NPM_TOKEN == '' }}
        run: |
          echo "NPM_TOKEN secret is required to publish" >&2
          exit 1

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun test

      - name: Build
        run: bun run build

      - name: Bump version
        id: bump
        run: |
          VERSION=$(bun run version:bump --type "$BUMP_TYPE" --preid "$PREID")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Commit prerelease
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(release-beta): v${{ steps.bump.outputs.version }}"
            git push
          fi

      - name: Create tag
        run: |
          if git rev-parse "v${{ steps.bump.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag already exists"
          else
            git tag "v${{ steps.bump.outputs.version }}"
            git push origin "v${{ steps.bump.outputs.version }}"
          fi

      - name: Publish to npm (beta tag)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --tag "$DIST_TAG"
