// AUTO-GENERATED by scripts/update-catalog.ts - Do not edit manually
// Last updated: 2026-01-27T20:23:34.951Z

export type ProviderId = 'openai' | 'anthropic' | 'moonshot';

export interface ModelCost {
	input?: number;
	output?: number;
	cacheRead?: number;
	cacheWrite?: number;
}

export interface ModelLimit {
	context?: number;
	output?: number;
}

export interface ModelInfo {
	id: string;
	label?: string;
	cost?: ModelCost;
	limit?: ModelLimit;
	toolCall?: boolean;
	reasoning?: boolean;
}

export interface ProviderEntry {
	id: ProviderId;
	models: ModelInfo[];
}

export const catalog: Record<ProviderId, ProviderEntry> = {
	openai: {
		id: 'openai',
		models: [
			{
				id: 'codex-mini-latest',
				label: 'Codex Mini',
				cost: {
					input: 1.5,
					output: 6,
					cacheRead: 0.375,
				},
				limit: {
					context: 200000,
					output: 100000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5',
				label: 'GPT-5',
				cost: {
					input: 1.25,
					output: 10,
					cacheRead: 0.125,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5-chat-latest',
				label: 'GPT-5 Chat (latest)',
				cost: {
					input: 1.25,
					output: 10,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: false,
				reasoning: true,
			},
			{
				id: 'gpt-5-codex',
				label: 'GPT-5-Codex',
				cost: {
					input: 1.25,
					output: 10,
					cacheRead: 0.125,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5-mini',
				label: 'GPT-5 Mini',
				cost: {
					input: 0.25,
					output: 2,
					cacheRead: 0.025,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5-nano',
				label: 'GPT-5 Nano',
				cost: {
					input: 0.05,
					output: 0.4,
					cacheRead: 0.005,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5-pro',
				label: 'GPT-5 Pro',
				cost: {
					input: 15,
					output: 120,
				},
				limit: {
					context: 400000,
					output: 272000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.1',
				label: 'GPT-5.1',
				cost: {
					input: 1.25,
					output: 10,
					cacheRead: 0.13,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.1-chat-latest',
				label: 'GPT-5.1 Chat',
				cost: {
					input: 1.25,
					output: 10,
					cacheRead: 0.125,
				},
				limit: {
					context: 128000,
					output: 16384,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.1-codex',
				label: 'GPT-5.1 Codex',
				cost: {
					input: 1.25,
					output: 10,
					cacheRead: 0.125,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.1-codex-max',
				label: 'GPT-5.1 Codex Max',
				cost: {
					input: 1.25,
					output: 10,
					cacheRead: 0.125,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.1-codex-mini',
				label: 'GPT-5.1 Codex mini',
				cost: {
					input: 0.25,
					output: 2,
					cacheRead: 0.025,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.2',
				label: 'GPT-5.2',
				cost: {
					input: 1.75,
					output: 14,
					cacheRead: 0.175,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.2-chat-latest',
				label: 'GPT-5.2 Chat',
				cost: {
					input: 1.75,
					output: 14,
					cacheRead: 0.175,
				},
				limit: {
					context: 128000,
					output: 16384,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.2-codex',
				label: 'GPT-5.2 Codex',
				cost: {
					input: 1.75,
					output: 14,
					cacheRead: 0.175,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'gpt-5.2-pro',
				label: 'GPT-5.2 Pro',
				cost: {
					input: 21,
					output: 168,
				},
				limit: {
					context: 400000,
					output: 128000,
				},
				toolCall: true,
				reasoning: true,
			},
		],
	},
	anthropic: {
		id: 'anthropic',
		models: [
			{
				id: 'claude-3-5-haiku-20241022',
				label: 'Claude Haiku 3.5',
				cost: {
					input: 0.8,
					output: 4,
					cacheRead: 0.08,
					cacheWrite: 1,
				},
				limit: {
					context: 200000,
					output: 8192,
				},
				toolCall: true,
				reasoning: false,
			},
			{
				id: 'claude-3-5-haiku-latest',
				label: 'Claude Haiku 3.5 (latest)',
				cost: {
					input: 0.8,
					output: 4,
					cacheRead: 0.08,
					cacheWrite: 1,
				},
				limit: {
					context: 200000,
					output: 8192,
				},
				toolCall: true,
				reasoning: false,
			},
			{
				id: 'claude-3-5-sonnet-20240620',
				label: 'Claude Sonnet 3.5',
				cost: {
					input: 3,
					output: 15,
					cacheRead: 0.3,
					cacheWrite: 3.75,
				},
				limit: {
					context: 200000,
					output: 8192,
				},
				toolCall: true,
				reasoning: false,
			},
			{
				id: 'claude-3-5-sonnet-20241022',
				label: 'Claude Sonnet 3.5 v2',
				cost: {
					input: 3,
					output: 15,
					cacheRead: 0.3,
					cacheWrite: 3.75,
				},
				limit: {
					context: 200000,
					output: 8192,
				},
				toolCall: true,
				reasoning: false,
			},
			{
				id: 'claude-haiku-4-5',
				label: 'Claude Haiku 4.5 (latest)',
				cost: {
					input: 1,
					output: 5,
					cacheRead: 0.1,
					cacheWrite: 1.25,
				},
				limit: {
					context: 200000,
					output: 64000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-haiku-4-5-20251001',
				label: 'Claude Haiku 4.5',
				cost: {
					input: 1,
					output: 5,
					cacheRead: 0.1,
					cacheWrite: 1.25,
				},
				limit: {
					context: 200000,
					output: 64000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-opus-4-0',
				label: 'Claude Opus 4 (latest)',
				cost: {
					input: 15,
					output: 75,
					cacheRead: 1.5,
					cacheWrite: 18.75,
				},
				limit: {
					context: 200000,
					output: 32000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-opus-4-1',
				label: 'Claude Opus 4.1 (latest)',
				cost: {
					input: 15,
					output: 75,
					cacheRead: 1.5,
					cacheWrite: 18.75,
				},
				limit: {
					context: 200000,
					output: 32000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-opus-4-1-20250805',
				label: 'Claude Opus 4.1',
				cost: {
					input: 15,
					output: 75,
					cacheRead: 1.5,
					cacheWrite: 18.75,
				},
				limit: {
					context: 200000,
					output: 32000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-opus-4-20250514',
				label: 'Claude Opus 4',
				cost: {
					input: 15,
					output: 75,
					cacheRead: 1.5,
					cacheWrite: 18.75,
				},
				limit: {
					context: 200000,
					output: 32000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-opus-4-5',
				label: 'Claude Opus 4.5 (latest)',
				cost: {
					input: 5,
					output: 25,
					cacheRead: 0.5,
					cacheWrite: 6.25,
				},
				limit: {
					context: 200000,
					output: 64000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-opus-4-5-20251101',
				label: 'Claude Opus 4.5',
				cost: {
					input: 5,
					output: 25,
					cacheRead: 0.5,
					cacheWrite: 6.25,
				},
				limit: {
					context: 200000,
					output: 64000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-sonnet-4-0',
				label: 'Claude Sonnet 4 (latest)',
				cost: {
					input: 3,
					output: 15,
					cacheRead: 0.3,
					cacheWrite: 3.75,
				},
				limit: {
					context: 200000,
					output: 64000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-sonnet-4-20250514',
				label: 'Claude Sonnet 4',
				cost: {
					input: 3,
					output: 15,
					cacheRead: 0.3,
					cacheWrite: 3.75,
				},
				limit: {
					context: 200000,
					output: 64000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-sonnet-4-5',
				label: 'Claude Sonnet 4.5 (latest)',
				cost: {
					input: 3,
					output: 15,
					cacheRead: 0.3,
					cacheWrite: 3.75,
				},
				limit: {
					context: 200000,
					output: 64000,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'claude-sonnet-4-5-20250929',
				label: 'Claude Sonnet 4.5',
				cost: {
					input: 3,
					output: 15,
					cacheRead: 0.3,
					cacheWrite: 3.75,
				},
				limit: {
					context: 200000,
					output: 64000,
				},
				toolCall: true,
				reasoning: true,
			},
		],
	},
	moonshot: {
		id: 'moonshot',
		models: [
			{
				id: 'kimi-k2-0711-preview',
				label: 'Kimi K2 0711',
				cost: {
					input: 0.6,
					output: 2.5,
					cacheRead: 0.15,
				},
				limit: {
					context: 131072,
					output: 16384,
				},
				toolCall: true,
				reasoning: false,
			},
			{
				id: 'kimi-k2-0905-preview',
				label: 'Kimi K2 0905',
				cost: {
					input: 0.6,
					output: 2.5,
					cacheRead: 0.15,
				},
				limit: {
					context: 262144,
					output: 262144,
				},
				toolCall: true,
				reasoning: false,
			},
			{
				id: 'kimi-k2-thinking',
				label: 'Kimi K2 Thinking',
				cost: {
					input: 0.6,
					output: 2.5,
					cacheRead: 0.15,
				},
				limit: {
					context: 262144,
					output: 262144,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'kimi-k2-thinking-turbo',
				label: 'Kimi K2 Thinking Turbo',
				cost: {
					input: 1.15,
					output: 8,
					cacheRead: 0.15,
				},
				limit: {
					context: 262144,
					output: 262144,
				},
				toolCall: true,
				reasoning: true,
			},
			{
				id: 'kimi-k2-turbo-preview',
				label: 'Kimi K2 Turbo',
				cost: {
					input: 2.4,
					output: 10,
					cacheRead: 0.6,
				},
				limit: {
					context: 262144,
					output: 262144,
				},
				toolCall: true,
				reasoning: false,
			},
			{
				id: 'kimi-k2.5',
				label: 'Kimi K2.5',
				cost: {
					input: 0.6,
					output: 3,
					cacheRead: 0.1,
					cacheWrite: 0.6,
				},
				limit: {
					context: 262144,
					output: 262144,
				},
				toolCall: true,
				reasoning: true,
			},
		],
	},
};
